### ISSUE TITLE
As a participant I want to get a Confirmation message about the upload, because I want to be sure that nothing failed

### ISSUE THREAD

**Issue by AdelwoehrerLeonie** [ContestSubmission/Documentation#1]

**Comment by SIMULATAN** [comment]
Can be considered implemented in ContestSubmission/Frontend#

**Comment by SIMULATAN** [comment]
Can be considered as "implemented" after https://github.com/ContestSubmission/Frontend/commit/5bb5cd86299918ee3cfdf1dbb2314c87924f0a15
